name: CI/CD
on:
  push:
    branches: [main]
  workflow_dispatch: 
jobs:
  build:
    # always windows. why would you use wsl on linux or macos 😂
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: vedantmgoyal9/setup-wsl2@main
        with:        
          distro: Alpine
      - run: curl -fsSL https://ollama.com/install.sh | sh
        shell: wsl-run {0} # add this to run the commands inside linux
      - run: |
          wsl --export Alpine ollama.tar
      - run: |
          ls -la
